# Creating a Tensor

In [1]:
# Load library
import torch

In [2]:
# Create a vector as a row
tensor_row = torch.tensor([1,2,3])
tensor_row

tensor([1, 2, 3])

In [3]:
# Create a vector as a column
tensor_column = torch.tensor([[1],[2],[3]])
tensor_column

tensor([[1],
        [2],
        [3]])

# Creating a Tensor from Numpy

In [4]:
import numpy as np
import torch

In [6]:
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [8]:
tensor_row = torch.from_numpy(vector_row)
tensor_row

tensor([1, 2, 3])

# Creating a Sparse Tensor

In [15]:
import torch

tensor = torch.tensor([
    [0,0],
    [0,1],
    [3,0]
])
sparse_tensor = tensor.to_sparse()
sparse_tensor

tensor(indices=tensor([[1, 2],
                       [1, 0]]),
       values=tensor([1, 3]),
       size=(3, 2), nnz=2, layout=torch.sparse_coo)

In [16]:
print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


# Selecting Elements in a Tensor

In [18]:
# Load library
import torch

In [22]:
# Create vector tensor
vector = torch.tensor([1,2,3,4,5,6])

# Create matrix tensor
matrix = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Select the third element of vector
vector[2]

tensor(3)

In [23]:
# Select second row, second column
matrix[1,1]

tensor(5)

In [25]:
# Select all elements of a vector
vector[:3]

tensor([1, 2, 3])

In [26]:
# Select everything after the third element
vector[3:]

tensor([4, 5, 6])

In [27]:
# Select the last element
vector[-1]

tensor(6)

In [28]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# Select all rows and the second column
matrix[:,1:2]

tensor([[2],
        [5],
        [8]])

In [31]:
# Reverse the vector: notice PyTorch tensors do not support negative indexes when slicing. 
# Therefore attempting to reverse a vector results in this error.
vector[::-1]

ValueError: step must be greater than zero

In [32]:
# To Reverse a vector:
vector.flip(dims=(-1,))

tensor([6, 5, 4, 3, 2, 1])

# Describing a Tensor

In [33]:
# Load library
import torch

In [34]:
# Create a tensor
tensor = torch.tensor([[1,2,3], [1,2,3]])

In [35]:
# Describe the shape of a tensor
tensor.shape

torch.Size([2, 3])

In [36]:
# Get the datatype of items in the tensor
tensor.dtype

torch.int64

In [38]:
# Get the layout of the tensor (strided vs. sparse)
tensor.layout

torch.strided

In [39]:
# Get the device being used by the tensor
tensor.device

device(type='cpu')

# Applying Operations to Elements

In [40]:
# Load library
import torch

In [41]:
# Create a tensor
tensor = torch.tensor([1,2,3])

In [42]:
# Broadcast an arithmetic operation to all elements in a tensor
tensor * 100

tensor([100, 200, 300])

In [43]:
# Load library
import torch

In [44]:
# Create a tensor
torch.tensor([1,2,3])

# Find the largest value
tensor.max()

tensor(3)

In [46]:
# Find the smallest value
tensor.min()

tensor(1)

In [47]:
# Create a multidimensional tensor
tensor = torch.tensor([[1,2,3],[1,2,5]])

In [49]:
tensor.max()

tensor(5)

# Reshaping Tensors

In [50]:
# Load library
import torch

In [54]:
# Create 4x3 tensor
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
tensor.shape

torch.Size([4, 3])

In [58]:
tensor.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [60]:
tensor.reshape(2,6).shape

torch.Size([2, 6])

# Transposing a Tensor

In [62]:
# Load library
import torch

In [63]:
# Create a 2-dimensional tensor
tensor = torch.tensor([[[1,2,3]]])

In [64]:
# Transpose the tensor
tensor.mT

tensor([[[1],
         [2],
         [3]]])

In [65]:
# An additional way to transpose PyTorch tensors of any shape
tensor.permute(*torch.arange(tensor.ndim -1, -1, -1))

tensor([[[1]],

        [[2]],

        [[3]]])

# Flattening a Tensor

In [67]:
# Load library
import torch

In [68]:
# Create tensor
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

# Flatten tensor
tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculating Dot Products

In [70]:
# Load library
import torch

# Create one tensor
tensor_1 = torch.tensor([1,2,3])

# Create another tensor
tensor_2 = torch.tensor([4,5,6])

In [71]:
# Calculate the dot product of the two tensors
tensor_1.dot(tensor_2)

tensor(32)

# Multiplying Tensors

In [73]:
# Load library
import torch

# Create one tensor
tensor_1 = torch.tensor([1,2,3])

# Create another tensor
tensor_2 = torch.tensor([4,5,6])

# Multiply the two tensors
tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [75]:
# adding one tensor to another:
tensor_1 + tensor_2

tensor([5, 7, 9])

In [76]:
# subtracting one tensor from another:
tensor_1-tensor_2

tensor([-3, -3, -3])

In [77]:
# divide one tensor by another:
tensor_1/tensor_2

tensor([0.2500, 0.4000, 0.5000])